version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: accounting_db
      MYSQL_USER: cloud
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
